### ISSUE TITLE
document file needed

### ISSUE THREAD

**Issue by ShriDemo** [Kavithaashri/whatsup_Development#3]
hello Kavithaashri,
If the application is capable of having document files it will more advantage, Pls add the feature.

**Comment by Kavithaashri** [comment]
Hi shriLearning,
Thanks for giving your valuable feedback.will do it

**Comment by Kavithaashri** [comment]
dear shrilearning,
document field has been added.Thanks for sharing your feedback

**Comment by ShriDemo** [comment]
Dear Kavithaashri,
Thank you
